config/routes.rb
Rails.application.routes.draw do
  get '/savings', to: 'savings#index'
  get 'categories', to: "categories#index"
  get 'categories/:name', to: "categories#show", as: :category
  devise_for :users
  resources :resources do
    resources :comments, only: [:create]
    resources :votes, only: [:create]
  end
  root to: 'resources#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :resource
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, length: {minimum: 2, maximum:20}
	has_many :categorizations, dependent: :destroy
	has_many :resources, through: :categorizations

  def to_s
    name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :resource

  validates :body, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :categorizations, dependent: :destroy
	has_many :categories, through: :categorizations
	has_many :votes, dependent: :destroy
  has_many :savings
	has_many :savers, through: :savings, source: :user

	validates :title, presence: true
	validates :link, presence: true
	validates :notes, presence: true, length: {minimum: 10, maximum: 140}

	default_scope -> { order(created_at: :desc) }

	def category_list=(category_string)
    category_names = category_string.split(',').collect { |s| s.strip }.uniq
    new_or_found_categories = category_names.collect { |name| Category.find_or_create_by(name: name) }
		self.categories = new_or_found_categories
	end

  def self.already_voted?(resource, user_id)
    Vote.exists?(user_id: user_id, resource_id: resource.id)
  end
end

app/models/saved_resource.rb
class SavedResource < ApplicationRecord
  belongs_to :resource
  belongs_to :user
end

app/models/saving.rb
class Saving < ApplicationRecord
  belongs_to :resource
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length:{minimum: 5, maximum: 10}

  has_many :resources
  has_many :comments
  has_many :votes
  has_many :savings
  has_many :saved_resources, through: :savings, source: :resource
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :resource, counter_cache: true
  
  validates :user_id, uniqueness: { scope: :resource_id }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(name: params[:name])
    @resources = @category.resources
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    resource = params[:resource_id]
    @comment = current_user.comments.build(comment_params)
    @comment.resource_id = resource

    if @comment.save
      redirect_to resource_path(resource)
    end    
  end
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  def index
    @resources = Resource.includes(:categories).all
  end

  def show
    @new_comment = @resource.comments.new
    @comments = @resource.comments.includes(:user)
  end
  
  def new
    @resource = Resource.new
  end

  def edit
  end

  def create
    @resource = current_user.resources.build(resource_params)
    if @resource.save
      flash[:success] = "Resource successfully created!"
      redirect_to @resource
    else
      flash[:error] = "Something went wrong."
      render 'new'
    end
  end

  def update
    if @resource.update_attributes(resource_params)
      flash[:success] = "Resource was successfully updated!"
      redirect_to @resource
    else
      flash[:error] = "Something went wrong."
      render 'edit'
    end
  end

  def destroy
    if @resource.destroy
      flash[:success] = 'Resource was successfully deleted.'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong.'
      redirect_to @resource
    end
  end  
  
  private
  
  def set_resource
    @resource = Resource.find(params[:id])
  end

  def resource_params
    params.require(:resource).permit(:title, :link, :notes, :category_list)
  end
end

app/controllers/savings_controller.rb
class SavingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @saved_resources = current_user.saved_resources
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @vote = current_user.votes.build(resource_id: params[:resource_id])

    if @vote.save
      redirect_back fallback_location: root_path, notice: 'You voted for this resource'
    else
      redirect_back fallback_location: root_path, notice: 'You already voted for this resource'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_vote_for(resource, user)
    vote_count = if resource.votes_count.nil?
                   0
                 else
                   resource.votes_count
                 end
    
    if user.nil?
      content_tag(:p, class: 'voted') do
        "<i class='far fa-heart'></i> #{vote_count}".html_safe
      end
    else
      vote_status = Resource.already_voted?(resource, user.id)    

      if vote_status
        content_tag(:p, class: 'voted') do
          "<i class='fas fa-heart'></i> #{vote_count}".html_safe
        end
      else
        link_to(resource_votes_path(resource), method: :post, class: 'vote') do
          "<i class='far fa-heart'></i> #{vote_count}".html_safe
        end
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/savings_helper.rb
module SavingsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<%= link_to 'Home', root_path %> | 
<%= link_to 'Categories', categories_path %> | 
<%= link_to 'New Resource', new_resource_path %> | 

<% if user_signed_in? %> 
    <%= link_to 'Saved Resources', savings_path %> | 
    <%= current_user.name %>
    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Sign_up', new_user_registration_path %>
    <%= link_to 'Sign_in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResourcesRepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/resources/_comment_form.html.erb
<%= form_with(model: [@resource, @new_comment], local: true) do |f| %>
  <% if @new_comment.errors.any? %>
    <div class="alert">
      <h4><%= pluralize(@new_commnet.errors.count, "error") %> prohibited this article from being saved:</h4>

      <% @new_commnet.errors.full_messages.each do |message| %>
        <div class="alert-text"><%= message %></div>
      <% end %>
    </div>
  <% end %>
  
	<div class="field">
		<%= f.label :body, "" %><br>
		<%= f.text_area :body, required: true %>
	</div>
  
	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/resources/_comments_list.html.erb
<% comments.each do |comment| %>
  <hr>
  <div>
    <strong><%= comment.user.name %></strong>
    <p><%= comment.body %></p>
  </div>
  <hr>
<% end %>

app/views/resources/_form.html.erb
<%= form_with(model: @resource, local: true) do |f| %>

	<% if @resource.errors.any? %>
    <div class="alert">
      <h4><%= pluralize(@resource.errors.count, "error") %> prohibited this article from being saved:</h4>

      <% @resource.errors.full_messages.each do |message| %>
        <div class="alert-text"><%= message %></div>
      <% end %>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :title, "Title:*" %><br>
		<%= f.text_field :title, required: true %>
	</div>
	
	<div class="field">
		<%= f.label :link, "Link:*" %><br>
		<%= f.text_field :link, required: true %>
	</div>
	
	<div class="field">
		<%= f.label :notes, "Notes:*" %><br>
		<%= f.text_area :notes, required: true %>
	</div>
    
	<div class="field">
		<%= f.label :category_list, "Categories:*" %>
		<br>
		<%= f.text_field :category_list, placeholder: 'Input categories separated by commas', class: "input", required: true %>
	</div>
    
	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/resources/edit.html.erb
<h1>Edit resource</h1>

<%= render 'form' %>

app/views/resources/index.html.erb
<h1>Resources</h1>

<div>
  <%= render partial: 'shared/resources', locals: {resources: @resources} %>
</div>

app/views/resources/new.html.erb
<h1>Create new resource</h1>
<%= render 'form' %>

app/views/resources/show.html.erb
<h1>Resource</h1>

<h3><%= @resource.title %></h3>
<% @resource.categories.each do |category| %>
  <%= link_to category.name, category_path(category.name) %>      
<% end %>
<br>
<%= link_to @resource.link, @resource.link, target: "_blank" %>

<p><%= @resource.notes %></p>


<%= link_to 'View all resources', root_path %> |
<% if current_user &.== @resource.user %>
  <%= link_to 'Edit', edit_resource_path %> |
  <%= link_to 'Delete', @resource, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<h4>Comments</h4>

<%= render 'comment_form' %>

<%= render partial: 'comments_list', locals: {comments: @comments} %>

app/views/shared/_resources.html.erb
<% resources.each do |resource| %>
  <hr>
  <div>
    <h3><%= resource.title %></h3>
    <% resource.categories.each do |category| %>
      <%= link_to category.name, category_path(category.name) %>      
    <% end %>
    <br>
    
    <%= link_to resource.link, resource.link, target: "_blank" %>

    <p><%= resource.notes.truncate(30) %></p>
    <%= display_vote_for(resource, current_user) %>
  </div>
  <%= link_to 'Show',  resource %>  
  <hr>
<% end %>